In [1]:
import requests
import pandas as pd

In [2]:
case_id = "57a1604c-60b7-4b30-a75e-f70939532c5c"

url = f"https://api.gdc.cancer.gov/cases/{case_id}"

params = {
    "expand": "demographic,diagnoses",
    "pretty": "true"
}

response = requests.get(url, params=params)
response.raise_for_status()

case = response.json()["data"]

case

{'slide_ids': ['643fd386-3bcb-4ee1-a030-1e34eeefeb04',
  'b3643e0d-dc70-4fd2-a0e0-534890f73da1'],
 'submitter_slide_ids': ['TCGA-BH-A0B2-01A-01-TSA', 'TCGA-BH-A0B2-01A-01-BSA'],
 'disease_type': 'Ductal and Lobular Neoplasms',
 'analyte_ids': ['97f3d921-4fe1-40ad-9f84-e0537372ad3f',
  'c7efa2f3-6724-4cc6-a375-4c6026c019e9',
  'e4b5ef86-2bda-4498-a4f0-42d1a0a65a05',
  '41054d29-473d-4db6-9523-feb4000486a2',
  'fe787c20-f983-4e10-a08b-72a48d07e303'],
 'submitter_id': 'TCGA-BH-A0B2',
 'submitter_analyte_ids': ['TCGA-BH-A0B2-01A-11R',
  'TCGA-BH-A0B2-01A-11D',
  'TCGA-BH-A0B2-10A-01D',
  'TCGA-BH-A0B2-01A-11W',
  'TCGA-BH-A0B2-10A-01W'],
 'aliquot_ids': ['30143b3f-7a18-446f-b3b9-18a6748d7155',
  '760f4cd1-ad18-4acd-a1c9-a9c3f396658d',
  '0a8c0095-44df-4b5e-9479-4a9920692a06',
  'a27c5907-1ad2-4414-a9c9-448f1b484946',
  'de5fed7f-9770-4cb3-85bd-1b0bec7440da',
  '3a713c13-5bc4-4d9c-9e6f-85b2aaa8d85e',
  'ae2856f4-dafc-45b6-96af-6c6615cf9475',
  'd56e6268-4f07-457e-87f4-fb87d8d33c5a',
  '80c5eea0-7133-4894-a74a-218193e2d5c9',
  '298580bc-ef73-44cb-91e3-923f74c9d5b5',
  '91bd1854-4e4d-4bd9-baea-9d7505bd6b0c'],
 'submitter_aliquot_ids': ['TCGA-BH-A0B2-01A-11D-A10M-09',
  'TCGA-BH-A0B2-01A-11D-A10L-01',
  'TCGA-BH-A0B2-10A-01W-A124-09',
  'TCGA-BH-A0B2-01A-11D-A10K-02',
  'TCGA-BH-A0B2-01A-11D-A10N-05',
  'TCGA-BH-A0B2-10A-01D-A10L-01',
  'TCGA-BH-A0B2-01A-11R-A10J-07',
  'TCGA-BH-A0B2-01A-11R-A10I-13',
  'TCGA-BH-A0B2-01A-11W-A124-09',
  'TCGA-BH-A0B2-10A-01D-A10K-02',
  'TCGA-BH-A0B2-10A-01D-A10M-09'],
 'created_datetime': None,
 'sample_ids': ['d2b1e8d2-304a-43cf-afb9-e7c0a69fff03',
  '35071558-5a5f-450d-bbf0-6b5a3b481c2f'],
 'submitter_sample_ids': ['TCGA-BH-A0B2-10A', 'TCGA-BH-A0B2-01A'],
 'primary_site': 'Breast',
 'updated_datetime': '2019-05-01T11:44:31.171098-05:00',
 'case_id': '57a1604c-60b7-4b30-a75e-f70939532c5c',
 'state': 'released',
 'portion_ids': ['2cdcaddf-2dd3-492b-a08f-71adc1065fec',
  '312152e4-98f1-461d-b489-4540ae5e56f0',
  '4bf32f04-810d-44c3-893f-6b33010b7435',
  '18dfaf42-20e5-4c56-9481-d645d41975b1'],
 'submitter_portion_ids': ['TCGA-BH-A0B2-01A-11',
  'TCGA-BH-A0B2-10A-01',
  'TCGA-BH-A0B2-01A-21',
  'TCGA-BH-A0B2-01A-21-A13C-20']}

In [3]:
case.keys()

dict_keys(['slide_ids', 'submitter_slide_ids', 'disease_type', 'analyte_ids', 'submitter_id', 'submitter_analyte_ids', 'aliquot_ids', 'submitter_aliquot_ids', 'created_datetime', 'sample_ids', 'submitter_sample_ids', 'primary_site', 'updated_datetime', 'case_id', 'state', 'portion_ids', 'submitter_portion_ids'])

In [4]:
import requests
import json

url = "https://api.gdc.cancer.gov/cases"

filters = {
    "op": "and",
    "content": [
        {
            "op": "=",
            "content": {
                "field": "project.project_id",
                "value": ["TCGA-BRCA"]
            }
        }
    ]
}

fields = [
    "case_id",
    "submitter_id",
    "demographic.gender",
    "demographic.sex_at_birth",
    "demographic.race",
    "demographic.ethnicity",
    "demographic.vital_status",
    "demographic.days_to_death",
    "demographic.year_of_birth",
    "demographic.year_of_death",
    "diagnoses.age_at_diagnosis",
    "diagnoses.primary_diagnosis",
    "diagnoses.ajcc_pathologic_stage",
    "diagnoses.ajcc_pathologic_t",
    "diagnoses.ajcc_pathologic_n",
    "diagnoses.ajcc_pathologic_m",
    "diagnoses.days_to_last_follow_up"
]

params = {
    "filters": json.dumps(filters),
    "fields": ",".join(fields),
    "format": "JSON",
    "size": 5
}

response = requests.get(url, params=params)
response.raise_for_status()

data = response.json()

data["data"]["hits"]

[{'id': '57a1604c-60b7-4b30-a75e-f70939532c5c',
  'case_id': '57a1604c-60b7-4b30-a75e-f70939532c5c',
  'submitter_id': 'TCGA-BH-A0B2'},
 {'id': '2779fa01-ac93-4e80-a997-3385f72172c3',
  'case_id': '2779fa01-ac93-4e80-a997-3385f72172c3',
  'submitter_id': 'TCGA-A8-A08S',
  'diagnoses': [{'age_at_diagnosis': None,
    'primary_diagnosis': 'Not Reported'},
   {'ajcc_pathologic_t': 'T1c',
    'days_to_last_follow_up': None,
    'age_at_diagnosis': 25994,
    'primary_diagnosis': 'Infiltrating duct carcinoma, NOS',
    'ajcc_pathologic_stage': 'Stage IIA',
    'ajcc_pathologic_n': 'N1',
    'ajcc_pathologic_m': 'M0'}],
  'demographic': {'race': 'not reported',
   'ethnicity': 'not reported',
   'vital_status': 'Alive',
   'sex_at_birth': 'female',
   'year_of_death': None,
   'year_of_birth': None}},
 {'id': '80f3f48a-cc21-415c-b181-c77e7ba1c563',
  'case_id': '80f3f48a-cc21-415c-b181-c77e7ba1c563',
  'submitter_id': 'TCGA-A8-A09C',
  'diagnoses': [{'ajcc_pathologic_t': 'T2',
    'days_to_last_follow_up': None,
    'age_at_diagnosis': 25355,
    'primary_diagnosis': 'Infiltrating duct carcinoma, NOS',
    'ajcc_pathologic_stage': 'Stage X',
    'ajcc_pathologic_n': 'N0',
    'ajcc_pathologic_m': 'MX'},
   {'age_at_diagnosis': None, 'primary_diagnosis': 'Carcinoma in situ, NOS'}],
  'demographic': {'race': 'not reported',
   'ethnicity': 'not reported',
   'vital_status': 'Alive',
   'sex_at_birth': 'female',
   'year_of_death': None,
   'year_of_birth': None}},
 {'id': 'e663954c-05a8-479a-a623-400c1eb5efc6',
  'case_id': 'e663954c-05a8-479a-a623-400c1eb5efc6',
  'submitter_id': 'TCGA-BH-A1F5',
  'diagnoses': [{'ajcc_pathologic_t': 'T1c',
    'days_to_last_follow_up': None,
    'age_at_diagnosis': 22842,
    'primary_diagnosis': 'Infiltrating duct carcinoma, NOS',
    'ajcc_pathologic_stage': 'Stage IIA',
    'ajcc_pathologic_n': 'N1a',
    'ajcc_pathologic_m': 'M0'},
   {'age_at_diagnosis': None,
    'primary_diagnosis': 'Combined small cell carcinoma'},
   {'age_at_diagnosis': None, 'primary_diagnosis': 'Not Reported'}],
  'demographic': {'race': 'white',
   'ethnicity': 'not hispanic or latino',
   'vital_status': 'Dead',
   'days_to_death': 2712,
   'sex_at_birth': 'female',
   'year_of_death': None,
   'year_of_birth': None}},
 {'id': '14b95463-2108-4921-afc2-e29eef52b18f',
  'case_id': '14b95463-2108-4921-afc2-e29eef52b18f',
  'submitter_id': 'TCGA-A2-A0YT',
  'diagnoses': [{'ajcc_pathologic_t': 'T4b',
    'days_to_last_follow_up': None,
    'age_at_diagnosis': 20482,
    'primary_diagnosis': 'Infiltrating duct carcinoma, NOS',
    'ajcc_pathologic_stage': 'Stage IIIB',
    'ajcc_pathologic_n': 'N2a',
    'ajcc_pathologic_m': 'M0'}],
  'demographic': {'race': 'white',
   'ethnicity': 'not hispanic or latino',
   'vital_status': 'Dead',
   'days_to_death': 723,
   'sex_at_birth': 'female',
   'year_of_death': None,
   'year_of_birth': None}}]

In [5]:
data["data"]["hits"][0].keys()

dict_keys(['id', 'case_id', 'submitter_id'])

In [6]:
import requests
import json

In [7]:
url = "https://api.gdc.cancer.gov/cases"

filters = {
    "op": "and",
    "content": [
        {
            "op": "=",
            "content": {
                "field": "project.project_id",
                "value": ["TCGA-BRCA"]
            }
        }
    ]
}

fields = [
    "case_id",
    "submitter_id",
    "demographic.gender",
    "demographic.sex_at_birth",
    "demographic.race",
    "demographic.ethnicity",
    "demographic.vital_status",
    "demographic.days_to_death",
    "demographic.year_of_birth",
    "demographic.year_of_death",
    "diagnoses.age_at_diagnosis",
    "diagnoses.primary_diagnosis",
    "diagnoses.ajcc_pathologic_stage",
    "diagnoses.ajcc_pathologic_t",
    "diagnoses.ajcc_pathologic_n",
    "diagnoses.ajcc_pathologic_m",
    "diagnoses.days_to_last_follow_up"
]

params = {
    "filters": json.dumps(filters),
    "fields": ",".join(fields),
    "format": "JSON",
    "size": 5
}

response = requests.get(url, params=params)
response.raise_for_status()

data = response.json()

In [8]:
print(params["fields"])

case_id,submitter_id,demographic.gender,demographic.sex_at_birth,demographic.race,demographic.ethnicity,demographic.vital_status,demographic.days_to_death,demographic.year_of_birth,demographic.year_of_death,diagnoses.age_at_diagnosis,diagnoses.primary_diagnosis,diagnoses.ajcc_pathologic_stage,diagnoses.ajcc_pathologic_t,diagnoses.ajcc_pathologic_n,diagnoses.ajcc_pathologic_m,diagnoses.days_to_last_follow_up

In [9]:
print(response.url)

https://api.gdc.cancer.gov/cases?filters=%7B%22op%22%3A+%22and%22%2C+%22content%22%3A+%5B%7B%22op%22%3A+%22%3D%22%2C+%22content%22%3A+%7B%22field%22%3A+%22project.project_id%22%2C+%22value%22%3A+%5B%22TCGA-BRCA%22%5D%7D%7D%5D%7D&fields=case_id%2Csubmitter_id%2Cdemographic.gender%2Cdemographic.sex_at_birth%2Cdemographic.race%2Cdemographic.ethnicity%2Cdemographic.vital_status%2Cdemographic.days_to_death%2Cdemographic.year_of_birth%2Cdemographic.year_of_death%2Cdiagnoses.age_at_diagnosis%2Cdiagnoses.primary_diagnosis%2Cdiagnoses.ajcc_pathologic_stage%2Cdiagnoses.ajcc_pathologic_t%2Cdiagnoses.ajcc_pathologic_n%2Cdiagnoses.ajcc_pathologic_m%2Cdiagnoses.days_to_last_follow_up&format=JSON&size=5

In [10]:
data["data"]["hits"][0]

{'id': '57a1604c-60b7-4b30-a75e-f70939532c5c',
 'case_id': '57a1604c-60b7-4b30-a75e-f70939532c5c',
 'submitter_id': 'TCGA-BH-A0B2'}

In [11]:
import requests
import json

url = "https://api.gdc.cancer.gov/cases"

payload = {
    "size": 5,
    "filters": {
        "op": "=",
        "content": {
            "field": "cases.project.project_id",
            "value": ["TCGA-BRCA"]
        }
    },
    "expand": "demographic,diagnoses",
    "fields": ",".join([
        "case_id",
        "submitter_id",
        "demographic.sex_at_birth",
        "demographic.race",
        "demographic.ethnicity",
        "demographic.vital_status",
        "demographic.days_to_death",
        "diagnoses.age_at_diagnosis",
        "diagnoses.primary_diagnosis",
        "diagnoses.ajcc_pathologic_stage",
        "diagnoses.ajcc_pathologic_t",
        "diagnoses.ajcc_pathologic_n",
        "diagnoses.ajcc_pathologic_m",
        "diagnoses.days_to_last_follow_up"
    ])
}

response = requests.post(
    url,
    headers={"Content-Type": "application/json"},
    json=payload
)

response.raise_for_status()

data_post = response.json()

data_post["data"]["hits"][0]

{'id': '57a1604c-60b7-4b30-a75e-f70939532c5c',
 'case_id': '57a1604c-60b7-4b30-a75e-f70939532c5c',
 'submitter_id': 'TCGA-BH-A0B2'}

In [12]:
from pathlib import Path

data_dir = Path("../data")

for file in data_dir.iterdir():
    print(file.name)

clinical.project-tcga-brca.2026-08-13.tar.gz
.DS_Store
.gitkeep
clinical.project-tcga-brca.2026-08-13

In [13]:
clinical_dir = data_dir / "clinical.project-tcga-brca.2026-08-13"

for file in clinical_dir.iterdir():
    print(file.name)

family_history.tsv
pathology_detail.tsv
clinical.tsv
follow_up.tsv
exposure.tsv

In [14]:
import pandas as pd

clinical_file = clinical_dir / "clinical.tsv"

clinical_df = pd.read_csv(
    clinical_file,
    sep="\t",
    low_memory=False
)

print("Shape:", clinical_df.shape)

clinical_df.head()

Shape: (5546, 202)

,project.project_id,cases.case_id,cases.consent_type,cases.days_to_consent,cases.days_to_lost_to_followup,cases.disease_type,cases.index_date,cases.lost_to_followup,cases.primary_site,cases.submitter_id,...,treatments.treatment_effect,treatments.treatment_effect_indicator,treatments.treatment_frequency,treatments.treatment_id,treatments.treatment_intent_type,treatments.treatment_or_therapy,treatments.treatment_outcome,treatments.treatment_outcome_duration,treatments.treatment_type,treatments.treatment_type_administered
0,TCGA-BRCA,001cef41-ff86-4d3f-a140-a647ac4b10a1,Informed Consent,-34,'--,Ductal and Lobular Neoplasms,Diagnosis,'--,Breast,TCGA-E2-A1IU,...,'--,'--,'--,1b884f21-eb24-467f-aba2-208af17070b9,Adjuvant,no,'--,'--,"Radiation Therapy, NOS",'--
1,TCGA-BRCA,001cef41-ff86-4d3f-a140-a647ac4b10a1,Informed Consent,-34,'--,Ductal and Lobular Neoplasms,Diagnosis,'--,Breast,TCGA-E2-A1IU,...,'--,'--,'--,27868bc3-23c8-5e85-a0e2-314e6cdf9b2a,Adjuvant,yes,Treatment Ongoing,'--,Hormone Therapy,'--
2,TCGA-BRCA,001cef41-ff86-4d3f-a140-a647ac4b10a1,Informed Consent,-34,'--,Ductal and Lobular Neoplasms,Diagnosis,'--,Breast,TCGA-E2-A1IU,...,'--,'--,'--,aedf144c-6b7b-4d76-a3cb-4271aef10f1d,First-Line Therapy,yes,'--,'--,"Surgery, NOS",'--
3,TCGA-BRCA,0045349c-69d9-4306-a403-c9c1fa836644,Informed Consent,76,'--,Adenomas and Adenocarcinomas,Diagnosis,'--,Breast,TCGA-A1-A0SB,...,'--,'--,'--,0a534cae-de91-5e77-a3e7-b52d46bd3966,First-Line Therapy,yes,'--,'--,"Surgery, NOS",'--
4,TCGA-BRCA,00807dae-9f4a-4fd1-aac2-82eb11bf2afb,Informed Consent,19,'--,Adnexal and Skin Appendage Neoplasms,Diagnosis,No,Breast,TCGA-A2-A04W,...,'--,'--,'--,024faa94-ec57-4d14-b919-62dcab409958,Adjuvant,yes,Treatment Ongoing,'--,Bisphosphonate Therapy,'--

In [15]:
clinical_df.columns.tolist()

['project.project_id',
 'cases.case_id',
 'cases.consent_type',
 'cases.days_to_consent',
 'cases.days_to_lost_to_followup',
 'cases.disease_type',
 'cases.index_date',
 'cases.lost_to_followup',
 'cases.primary_site',
 'cases.submitter_id',
 'demographic.age_at_index',
 'demographic.age_is_obfuscated',
 'demographic.cause_of_death',
 'demographic.cause_of_death_source',
 'demographic.country_of_birth',
 'demographic.country_of_residence_at_enrollment',
 'demographic.days_to_birth',
 'demographic.days_to_death',
 'demographic.demographic_id',
 'demographic.education_level',
 'demographic.ethnicity',
 'demographic.marital_status',
 'demographic.occupation_duration_years',
 'demographic.population_group',
 'demographic.race',
 'demographic.sex_at_birth',
 'demographic.submitter_id',
 'demographic.vital_status',
 'demographic.year_of_birth',
 'demographic.year_of_birth_range',
 'demographic.year_of_death',
 'diagnoses.adrenal_hormone',
 'diagnoses.age_at_diagnosis',
 'diagnoses.ajcc_clinical_m',
 'diagnoses.ajcc_clinical_n',
 'diagnoses.ajcc_clinical_stage',
 'diagnoses.ajcc_clinical_t',
 'diagnoses.ajcc_pathologic_m',
 'diagnoses.ajcc_pathologic_n',
 'diagnoses.ajcc_pathologic_stage',
 'diagnoses.ajcc_pathologic_t',
 'diagnoses.ajcc_serum_tumor_markers',
 'diagnoses.ajcc_staging_system_edition',
 'diagnoses.ann_arbor_b_symptoms',
 'diagnoses.ann_arbor_b_symptoms_described',
 'diagnoses.ann_arbor_b_symptoms_described_array',
 'diagnoses.ann_arbor_clinical_stage',
 'diagnoses.ann_arbor_extranodal_involvement',
 'diagnoses.ann_arbor_pathologic_stage',
 'diagnoses.best_overall_response',
 'diagnoses.burkitt_lymphoma_clinical_variant',
 'diagnoses.calgb_risk_group',
 'diagnoses.cancer_detection_method',
 'diagnoses.child_pugh_classification',
 'diagnoses.clark_level',
 'diagnoses.classification_of_tumor',
 'diagnoses.cog_liver_stage',
 'diagnoses.cog_neuroblastoma_risk_group',
 'diagnoses.cog_renal_stage',
 'diagnoses.cog_rhabdomyosarcoma_risk_group',
 'diagnoses.contiguous_organ_invaded',
 'diagnoses.days_to_best_overall_response',
 'diagnoses.days_to_diagnosis',
 'diagnoses.days_to_last_follow_up',
 'diagnoses.days_to_last_known_disease_status',
 'diagnoses.days_to_recurrence',
 'diagnoses.diagnosis_id',
 'diagnoses.diagnosis_is_primary_disease',
 'diagnoses.double_expressor_lymphoma',
 'diagnoses.double_hit_lymphoma',
 'diagnoses.eln_risk_classification',
 'diagnoses.enneking_msts_grade',
 'diagnoses.enneking_msts_metastasis',
 'diagnoses.enneking_msts_stage',
 'diagnoses.enneking_msts_tumor_site',
 'diagnoses.ensat_clinical_m',
 'diagnoses.ensat_pathologic_n',
 'diagnoses.ensat_pathologic_stage',
 'diagnoses.ensat_pathologic_t',
 'diagnoses.esophageal_columnar_dysplasia_degree',
 'diagnoses.esophageal_columnar_metaplasia_present',
 'diagnoses.fab_morphology_code',
 'diagnoses.figo_stage',
 'diagnoses.figo_staging_edition_year',
 'diagnoses.first_symptom_longest_duration',
 'diagnoses.first_symptom_prior_to_diagnosis',
 'diagnoses.gastric_esophageal_junction_involvement',
 'diagnoses.gleason_grade_group',
 'diagnoses.gleason_grade_tertiary',
 'diagnoses.gleason_patterns_percent',
 'diagnoses.gleason_score',
 'diagnoses.goblet_cells_columnar_mucosa_present',
 'diagnoses.icd_10_code',
 'diagnoses.igcccg_stage',
 'diagnoses.inpc_grade',
 'diagnoses.inpc_histologic_group',
 'diagnoses.inrg_stage',
 'diagnoses.inss_stage',
 'diagnoses.international_prognostic_index',
 'diagnoses.irs_group',
 'diagnoses.irs_stage',
 'diagnoses.ishak_fibrosis_score',
 'diagnoses.iss_stage',
 'diagnoses.last_known_disease_status',
 'diagnoses.laterality',
 'diagnoses.margin_distance',
 'diagnoses.margins_involved_site',
 'diagnoses.masaoka_stage',
 'diagnoses.max_tumor_bulk_site',
 'diagnoses.medulloblastoma_molecular_classification',
 'diagnoses.melanoma_known_primary',
 'diagnoses.metastasis_at_diagnosis',
 'diagnoses.method_of_diagnosis',
 'diagnoses.mitosis_karyorrhexis_index',
 'diagnoses.morphology',
 'diagnoses.ovarian_specimen_status',
 'diagnoses.ovarian_surface_involvement',
 'diagnoses.pediatric_kidney_staging',
 'diagnoses.peritoneal_fluid_cytological_status',
 'diagnoses.primary_diagnosis',
 'diagnoses.primary_gleason_grade',
 'diagnoses.prior_malignancy',
 'diagnoses.prior_treatment',
 'diagnoses.progression_or_recurrence',
 'diagnoses.residual_disease',
 'diagnoses.satellite_nodule_present',
 'diagnoses.secondary_gleason_grade',
 'diagnoses.site_of_resection_or_biopsy',
 'diagnoses.sites_of_involvement',
 'diagnoses.sites_of_involvement_count',
 'diagnoses.submitter_id',
 'diagnoses.supratentorial_localization',
 'diagnoses.synchronous_malignancy',
 'diagnoses.tissue_or_organ_of_origin',
 'diagnoses.tumor_burden',
 'diagnoses.tumor_confined_to_organ_of_origin',
 'diagnoses.tumor_depth',
 'diagnoses.tumor_focality',
 'diagnoses.tumor_grade',
 'diagnoses.tumor_grade_category',
 'diagnoses.tumor_of_origin',
 'diagnoses.tumor_regression_grade',
 'diagnoses.uicc_clinical_m',
 'diagnoses.uicc_clinical_n',
 'diagnoses.uicc_clinical_stage',
 'diagnoses.uicc_clinical_t',
 'diagnoses.uicc_pathologic_m',
 'diagnoses.uicc_pathologic_n',
 'diagnoses.uicc_pathologic_stage',
 'diagnoses.uicc_pathologic_t',
 'diagnoses.uicc_staging_system_edition',
 'diagnoses.ulceration_indicator',
 'diagnoses.weiss_assessment_findings',
 'diagnoses.weiss_assessment_score',
 'diagnoses.who_cns_grade',
 'diagnoses.who_nte_grade',
 'diagnoses.wilms_tumor_histologic_subtype',
 'diagnoses.year_of_diagnosis',
 'treatments.chemo_concurrent_to_radiation',
 'treatments.clinical_trial_indicator',
 'treatments.course_number',
 'treatments.days_to_treatment_end',
 'treatments.days_to_treatment_start',
 'treatments.drug_category',
 'treatments.embolic_agent',
 'treatments.initial_disease_status',
 'treatments.lesions_treated_number',
 'treatments.margin_distance',
 'treatments.margin_status',
 'treatments.margins_involved_site',
 'treatments.number_of_cycles',
 'treatments.number_of_fractions',
 'treatments.prescribed_dose',
 'treatments.prescribed_dose_units',
 'treatments.pretreatment',
 'treatments.protocol_identifier',
 'treatments.radiosensitizing_agent',
 'treatments.reason_treatment_ended',
 'treatments.reason_treatment_not_given',
 'treatments.regimen_or_line_of_therapy',
 'treatments.residual_disease',
 'treatments.route_of_administration',
 'treatments.submitter_id',
 'treatments.therapeutic_agents',
 'treatments.therapeutic_levels_achieved',
 'treatments.therapeutic_target_level',
 'treatments.timepoint_category',
 'treatments.treatment_anatomic_sites',
 'treatments.treatment_dose',
 'treatments.treatment_dose_max',
 'treatments.treatment_dose_units',
 'treatments.treatment_duration',
 'treatments.treatment_effect',
 'treatments.treatment_effect_indicator',
 'treatments.treatment_frequency',
 'treatments.treatment_id',
 'treatments.treatment_intent_type',
 'treatments.treatment_or_therapy',
 'treatments.treatment_outcome',
 'treatments.treatment_outcome_duration',
 'treatments.treatment_type',
 'treatments.treatment_type_administered']

In [16]:
keywords = [
    "gender",
    "sex",
    "race",
    "ethnicity",
    "vital",
    "death",
    "diagnosis",
    "age_at_diagnosis",
    "stage",
    "pathologic",
    "follow"
]

relevant_columns = [
    col for col in clinical_df.columns
    if any(keyword.lower() in col.lower() for keyword in keywords)
]

relevant_columns

['cases.days_to_lost_to_followup',
 'cases.lost_to_followup',
 'demographic.cause_of_death',
 'demographic.cause_of_death_source',
 'demographic.days_to_death',
 'demographic.ethnicity',
 'demographic.race',
 'demographic.sex_at_birth',
 'demographic.vital_status',
 'demographic.year_of_death',
 'diagnoses.age_at_diagnosis',
 'diagnoses.ajcc_clinical_stage',
 'diagnoses.ajcc_pathologic_m',
 'diagnoses.ajcc_pathologic_n',
 'diagnoses.ajcc_pathologic_stage',
 'diagnoses.ajcc_pathologic_t',
 'diagnoses.ann_arbor_clinical_stage',
 'diagnoses.ann_arbor_pathologic_stage',
 'diagnoses.cog_liver_stage',
 'diagnoses.cog_renal_stage',
 'diagnoses.days_to_diagnosis',
 'diagnoses.days_to_last_follow_up',
 'diagnoses.diagnosis_id',
 'diagnoses.diagnosis_is_primary_disease',
 'diagnoses.enneking_msts_stage',
 'diagnoses.ensat_pathologic_n',
 'diagnoses.ensat_pathologic_stage',
 'diagnoses.ensat_pathologic_t',
 'diagnoses.figo_stage',
 'diagnoses.first_symptom_prior_to_diagnosis',
 'diagnoses.igcccg_stage',
 'diagnoses.inrg_stage',
 'diagnoses.inss_stage',
 'diagnoses.irs_stage',
 'diagnoses.iss_stage',
 'diagnoses.masaoka_stage',
 'diagnoses.metastasis_at_diagnosis',
 'diagnoses.method_of_diagnosis',
 'diagnoses.primary_diagnosis',
 'diagnoses.uicc_clinical_stage',
 'diagnoses.uicc_pathologic_m',
 'diagnoses.uicc_pathologic_n',
 'diagnoses.uicc_pathologic_stage',
 'diagnoses.uicc_pathologic_t',
 'diagnoses.year_of_diagnosis']

In [17]:
from pathlib import Path
import pandas as pd

In [18]:
data_dir = Path("../data")

clinical_dir = data_dir / "clinical.project-tcga-brca.2026-08-13"

clinical_file = clinical_dir / "clinical.tsv"

clinical_df = pd.read_csv(
    clinical_file,
    sep="\t",
    low_memory=False
)

In [19]:
print(clinical_df.shape)

(5546, 202)

In [20]:
[col for col in clinical_df.columns
 if "submitter" in col.lower() or "case_id" in col.lower()]

['cases.case_id',
 'cases.submitter_id',
 'demographic.submitter_id',
 'diagnoses.submitter_id',
 'treatments.submitter_id']

In [21]:
print("Number of rows:", clinical_df.shape[0])
print("Number of columns:", clinical_df.shape[1])

Number of rows: 5546
Number of columns: 202

In [22]:
clinical_df["demographic.vital_status"].value_counts(dropna=False)

demographic.vital_status
Alive    4697
Dead      848
'--         1
Name: count, dtype: int64

In [23]:
clinical_df["cases.submitter_id"].nunique()

1098

In [24]:
clinical_df["cases.submitter_id"].value_counts().head(10)

cases.submitter_id
TCGA-GM-A2DA    40
TCGA-A2-A04P    33
TCGA-A2-A3XU    22
TCGA-A2-A3XY    21
TCGA-A2-A0EW    20
TCGA-AO-A03N    19
TCGA-E9-A2JS    19
TCGA-A2-A04V    17
TCGA-A2-A04Y    17
TCGA-AO-A0J9    17
Name: count, dtype: int64

In [25]:
patient_id = clinical_df["cases.submitter_id"].iloc[0]

clinical_df[
    clinical_df["cases.submitter_id"] == patient_id
][[
    "cases.submitter_id",
    "demographic.vital_status",
    "diagnoses.primary_diagnosis",
    "diagnoses.ajcc_pathologic_stage",
    "diagnoses.age_at_diagnosis"
]]

,cases.submitter_id,demographic.vital_status,diagnoses.primary_diagnosis,diagnoses.ajcc_pathologic_stage,diagnoses.age_at_diagnosis
0,TCGA-E2-A1IU,Alive,"Infiltrating duct carcinoma, NOS",Stage IA,22279
1,TCGA-E2-A1IU,Alive,"Infiltrating duct carcinoma, NOS",Stage IA,22279
2,TCGA-E2-A1IU,Alive,"Infiltrating duct carcinoma, NOS",Stage IA,22279

In [26]:
n_patients = clinical_df["cases.submitter_id"].nunique()

print("Total rows:", len(clinical_df))
print("Unique patients:", n_patients)

Total rows: 5546
Unique patients: 1098

In [27]:
clinical_df["cases.submitter_id"].value_counts().describe()

count    1098.000000
mean        5.051002
std         3.024534
min         1.000000
25%         3.000000
50%         5.000000
75%         6.000000
max        40.000000
Name: count, dtype: float64

In [28]:
clinical_df["cases.submitter_id"].value_counts().head(10)

cases.submitter_id
TCGA-GM-A2DA    40
TCGA-A2-A04P    33
TCGA-A2-A3XU    22
TCGA-A2-A3XY    21
TCGA-A2-A0EW    20
TCGA-AO-A03N    19
TCGA-E9-A2JS    19
TCGA-A2-A04V    17
TCGA-A2-A04Y    17
TCGA-AO-A0J9    17
Name: count, dtype: int64

In [29]:
clinical_selected = clinical_df[
    [
        "cases.case_id",
        "cases.submitter_id",
        "demographic.sex_at_birth",
        "demographic.race",
        "demographic.ethnicity",
        "demographic.vital_status",
        "demographic.days_to_death",
        "diagnoses.age_at_diagnosis",
        "diagnoses.primary_diagnosis",
        "diagnoses.ajcc_pathologic_stage",
        "diagnoses.ajcc_pathologic_t",
        "diagnoses.ajcc_pathologic_n",
        "diagnoses.ajcc_pathologic_m",
        "diagnoses.days_to_last_follow_up"
    ]
].copy()

clinical_selected.shape

(5546, 14)

In [30]:
clinical_selected = clinical_selected.rename(
    columns={
        "cases.case_id": "case_id",
        "cases.submitter_id": "patient_id",
        "demographic.sex_at_birth": "sex",
        "demographic.race": "race",
        "demographic.ethnicity": "ethnicity",
        "demographic.vital_status": "vital_status",
        "demographic.days_to_death": "days_to_death",
        "diagnoses.age_at_diagnosis": "age_at_diagnosis_days",
        "diagnoses.primary_diagnosis": "primary_diagnosis",
        "diagnoses.ajcc_pathologic_stage": "stage",
        "diagnoses.ajcc_pathologic_t": "pathologic_T",
        "diagnoses.ajcc_pathologic_n": "pathologic_N",
        "diagnoses.ajcc_pathologic_m": "pathologic_M",
        "diagnoses.days_to_last_follow_up": "days_to_last_follow_up"
    }
)

clinical_selected.head()

,case_id,patient_id,sex,race,ethnicity,vital_status,days_to_death,age_at_diagnosis_days,primary_diagnosis,stage,pathologic_T,pathologic_N,pathologic_M,days_to_last_follow_up
0,001cef41-ff86-4d3f-a140-a647ac4b10a1,TCGA-E2-A1IU,female,white,not hispanic or latino,Alive,'--,22279,"Infiltrating duct carcinoma, NOS",Stage IA,T1c,N0 (mol+),M0,'--
1,001cef41-ff86-4d3f-a140-a647ac4b10a1,TCGA-E2-A1IU,female,white,not hispanic or latino,Alive,'--,22279,"Infiltrating duct carcinoma, NOS",Stage IA,T1c,N0 (mol+),M0,'--
2,001cef41-ff86-4d3f-a140-a647ac4b10a1,TCGA-E2-A1IU,female,white,not hispanic or latino,Alive,'--,22279,"Infiltrating duct carcinoma, NOS",Stage IA,T1c,N0 (mol+),M0,'--
3,0045349c-69d9-4306-a403-c9c1fa836644,TCGA-A1-A0SB,female,white,not hispanic or latino,Alive,'--,25833,Adenoid cystic carcinoma,Stage I,T1c,N0,M0,'--
4,00807dae-9f4a-4fd1-aac2-82eb11bf2afb,TCGA-A2-A04W,female,white,not hispanic or latino,Alive,'--,18345,Apocrine adenocarcinoma,Stage IIB,T2,N1mi,M0,'--

In [31]:
clinical_unique_records = clinical_selected.drop_duplicates().copy()

print("Before removing exact duplicates:", len(clinical_selected))
print("After removing exact duplicates:", len(clinical_unique_records))
print(
    "Unique patients:",
    clinical_unique_records["patient_id"].nunique()
)

Before removing exact duplicates: 5546
After removing exact duplicates: 1331
Unique patients: 1098

In [32]:
records_per_patient = (
    clinical_unique_records
    .groupby("patient_id")
    .size()
    .sort_values(ascending=False)
)

records_per_patient.describe()

count    1098.000000
mean        1.212204
std         0.551419
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         7.000000
dtype: float64

In [33]:
records_per_patient.head(10)

patient_id
TCGA-A2-A04P    7
TCGA-GM-A2DA    5
TCGA-A2-A3XU    5
TCGA-E9-A1N6    4
TCGA-Z7-A8R5    4
TCGA-AR-A1AR    4
TCGA-A2-A3XY    4
TCGA-A7-A13G    4
TCGA-E2-A152    4
TCGA-A7-A26H    4
dtype: int64

In [34]:
multi_record_patient = records_per_patient.index[0]

clinical_unique_records[
    clinical_unique_records["patient_id"] == multi_record_patient
]

,case_id,patient_id,sex,race,ethnicity,vital_status,days_to_death,age_at_diagnosis_days,primary_diagnosis,stage,pathologic_T,pathologic_N,pathologic_M,days_to_last_follow_up
4396,ccd4a24b-d8cc-4686-9dee-c98b0c5a8d21,TCGA-A2-A04P,female,black or african american,not reported,Dead,548,13340,"Infiltrating duct carcinoma, NOS",'--,'--,'--,'--,'--
4399,ccd4a24b-d8cc-4686-9dee-c98b0c5a8d21,TCGA-A2-A04P,female,black or african american,not reported,Dead,548,13551,"Infiltrating duct carcinoma, NOS",'--,'--,'--,'--,'--
4402,ccd4a24b-d8cc-4686-9dee-c98b0c5a8d21,TCGA-A2-A04P,female,black or african american,not reported,Dead,548,13417,"Infiltrating duct carcinoma, NOS",'--,'--,'--,'--,'--
4405,ccd4a24b-d8cc-4686-9dee-c98b0c5a8d21,TCGA-A2-A04P,female,black or african american,not reported,Dead,548,13418,Not Reported,'--,'--,'--,'--,'--
4409,ccd4a24b-d8cc-4686-9dee-c98b0c5a8d21,TCGA-A2-A04P,female,black or african american,not reported,Dead,548,13418,"Infiltrating duct carcinoma, NOS",'--,'--,'--,'--,'--
4412,ccd4a24b-d8cc-4686-9dee-c98b0c5a8d21,TCGA-A2-A04P,female,black or african american,not reported,Dead,548,13417,Not Reported,'--,'--,'--,'--,'--
4416,ccd4a24b-d8cc-4686-9dee-c98b0c5a8d21,TCGA-A2-A04P,female,black or african american,not reported,Dead,548,13238,"Infiltrating duct carcinoma, NOS",Stage IIIC,T2,N3c,M0,'--

In [35]:
clinical_unique_records[
    clinical_unique_records["patient_id"] == multi_record_patient
][[
    "patient_id",
    "age_at_diagnosis_days",
    "primary_diagnosis",
    "stage",
    "pathologic_T",
    "pathologic_N",
    "pathologic_M",
    "days_to_last_follow_up",
    "vital_status",
    "days_to_death"
]]

,patient_id,age_at_diagnosis_days,primary_diagnosis,stage,pathologic_T,pathologic_N,pathologic_M,days_to_last_follow_up,vital_status,days_to_death
4396,TCGA-A2-A04P,13340,"Infiltrating duct carcinoma, NOS",'--,'--,'--,'--,'--,Dead,548
4399,TCGA-A2-A04P,13551,"Infiltrating duct carcinoma, NOS",'--,'--,'--,'--,'--,Dead,548
4402,TCGA-A2-A04P,13417,"Infiltrating duct carcinoma, NOS",'--,'--,'--,'--,'--,Dead,548
4405,TCGA-A2-A04P,13418,Not Reported,'--,'--,'--,'--,'--,Dead,548
4409,TCGA-A2-A04P,13418,"Infiltrating duct carcinoma, NOS",'--,'--,'--,'--,'--,Dead,548
4412,TCGA-A2-A04P,13417,Not Reported,'--,'--,'--,'--,'--,Dead,548
4416,TCGA-A2-A04P,13238,"Infiltrating duct carcinoma, NOS",Stage IIIC,T2,N3c,M0,'--,Dead,548

In [36]:
"diagnoses.diagnosis_is_primary_disease" in clinical_df.columns

True

In [37]:
clinical_df[
    clinical_df["cases.submitter_id"] == multi_record_patient
][[
    "cases.submitter_id",
    "diagnoses.primary_diagnosis",
    "diagnoses.diagnosis_is_primary_disease",
    "diagnoses.ajcc_pathologic_stage",
    "diagnoses.age_at_diagnosis"
]].drop_duplicates()

,cases.submitter_id,diagnoses.primary_diagnosis,diagnoses.diagnosis_is_primary_disease,diagnoses.ajcc_pathologic_stage,diagnoses.age_at_diagnosis
4396,TCGA-A2-A04P,"Infiltrating duct carcinoma, NOS",false,'--,13340
4399,TCGA-A2-A04P,"Infiltrating duct carcinoma, NOS",false,'--,13551
4402,TCGA-A2-A04P,"Infiltrating duct carcinoma, NOS",false,'--,13417
4405,TCGA-A2-A04P,Not Reported,false,'--,13418
4409,TCGA-A2-A04P,"Infiltrating duct carcinoma, NOS",false,'--,13418
4412,TCGA-A2-A04P,Not Reported,false,'--,13417
4416,TCGA-A2-A04P,"Infiltrating duct carcinoma, NOS",true,Stage IIIC,13238

In [38]:
clinical_selected = clinical_df[
    [
        "cases.case_id",
        "cases.submitter_id",
        "demographic.sex_at_birth",
        "demographic.race",
        "demographic.ethnicity",
        "demographic.vital_status",
        "demographic.days_to_death",

        "diagnoses.diagnosis_is_primary_disease",
        "diagnoses.age_at_diagnosis",
        "diagnoses.primary_diagnosis",
        "diagnoses.ajcc_pathologic_stage",
        "diagnoses.ajcc_pathologic_t",
        "diagnoses.ajcc_pathologic_n",
        "diagnoses.ajcc_pathologic_m",
        "diagnoses.days_to_last_follow_up"
    ]
].copy()

clinical_selected.shape

(5546, 15)

In [39]:
clinical_selected = clinical_selected.rename(
    columns={
        "cases.case_id": "case_id",
        "cases.submitter_id": "patient_id",
        "demographic.sex_at_birth": "sex",
        "demographic.race": "race",
        "demographic.ethnicity": "ethnicity",
        "demographic.vital_status": "vital_status",
        "demographic.days_to_death": "days_to_death",

        "diagnoses.diagnosis_is_primary_disease": "is_primary_diagnosis",
        "diagnoses.age_at_diagnosis": "age_at_diagnosis_days",
        "diagnoses.primary_diagnosis": "primary_diagnosis",
        "diagnoses.ajcc_pathologic_stage": "stage",
        "diagnoses.ajcc_pathologic_t": "pathologic_T",
        "diagnoses.ajcc_pathologic_n": "pathologic_N",
        "diagnoses.ajcc_pathologic_m": "pathologic_M",
        "diagnoses.days_to_last_follow_up": "days_to_last_follow_up"
    }
)

In [40]:
clinical_unique_records = clinical_selected.drop_duplicates().copy()

print("Before:", len(clinical_selected))
print("After exact duplicates:", len(clinical_unique_records))
print(
    "Unique patients:",
    clinical_unique_records["patient_id"].nunique()
)

Before: 5546
After exact duplicates: 1331
Unique patients: 1098

In [41]:
clinical_unique_records[
    "is_primary_diagnosis"
].value_counts(dropna=False)

is_primary_diagnosis
true     1096
false     233
'--         2
Name: count, dtype: int64

In [42]:
primary_flag = (
    clinical_unique_records["is_primary_diagnosis"]
    .astype(str)
    .str.lower()
    .eq("true")
)

patients_with_primary = (
    clinical_unique_records.loc[primary_flag, "patient_id"]
    .nunique()
)

total_patients = clinical_unique_records["patient_id"].nunique()

print("Total patients:", total_patients)
print("Patients with primary diagnosis flag:", patients_with_primary)
print(
    "Patients without primary diagnosis flag:",
    total_patients - patients_with_primary
)

Total patients: 1098
Patients with primary diagnosis flag: 1096
Patients without primary diagnosis flag: 2

In [43]:
patients_all = set(
    clinical_unique_records["patient_id"].dropna().unique()
)

patients_with_primary_set = set(
    clinical_unique_records.loc[
        primary_flag,
        "patient_id"
    ].dropna().unique()
)

patients_without_primary = sorted(
    patients_all - patients_with_primary_set
)

patients_without_primary

['TCGA-A7-A0DC', 'TCGA-BH-A0B2']

In [44]:
clinical_unique_records[
    clinical_unique_records["patient_id"].isin(
        patients_without_primary
    )
][[
    "patient_id",
    "is_primary_diagnosis",
    "primary_diagnosis",
    "age_at_diagnosis_days",
    "stage",
    "pathologic_T",
    "pathologic_N",
    "pathologic_M",
    "vital_status",
    "days_to_death",
    "days_to_last_follow_up"
]].sort_values("patient_id")

,patient_id,is_primary_diagnosis,primary_diagnosis,age_at_diagnosis_days,stage,pathologic_T,pathologic_N,pathologic_M,vital_status,days_to_death,days_to_last_follow_up
4368,TCGA-A7-A0DC,'--,"Infiltrating duct carcinoma, NOS",23294,Stage IA,T1c,N0 (i-),M0,Alive,'--,906.0
1820,TCGA-BH-A0B2,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--

In [45]:
primary_records = clinical_unique_records[
    primary_flag
].copy()

print("Rows:", len(primary_records))
print("Unique patients:", primary_records["patient_id"].nunique())

Rows: 1096
Unique patients: 1096

In [46]:
fallback_records = clinical_unique_records[
    clinical_unique_records["patient_id"].isin(
        patients_without_primary
    )
].copy()

print("Fallback rows:", len(fallback_records))
print("Fallback patients:", fallback_records["patient_id"].nunique())

Fallback rows: 2
Fallback patients: 2

In [47]:
clinical_patient = pd.concat(
    [primary_records, fallback_records],
    ignore_index=True
)

print("Rows:", len(clinical_patient))
print(
    "Unique patients:",
    clinical_patient["patient_id"].nunique()
)
print(
    "Duplicated patient IDs:",
    clinical_patient["patient_id"].duplicated().sum()
)

Rows: 1098
Unique patients: 1098
Duplicated patient IDs: 0

In [48]:
import numpy as np

clinical_patient = clinical_patient.replace(
    ["'--", "--", "Not Reported", "not reported"],
    np.nan
)

In [49]:
clinical_patient.isna().sum()

case_id                      0
patient_id                   0
sex                          1
race                        96
ethnicity                  167
vital_status                 1
days_to_death              947
is_primary_diagnosis         2
age_at_diagnosis_days       16
primary_diagnosis            1
stage                       12
pathologic_T                 1
pathologic_N                 1
pathologic_M                 1
days_to_last_follow_up    1097
dtype: int64

In [50]:
print("Rows:", len(clinical_patient))
print("Unique patients:", clinical_patient["patient_id"].nunique())
print("Duplicated IDs:", clinical_patient["patient_id"].duplicated().sum())

Rows: 1098
Unique patients: 1098
Duplicated IDs: 0

In [51]:
clinical_patient.isna().sum()

case_id                      0
patient_id                   0
sex                          1
race                        96
ethnicity                  167
vital_status                 1
days_to_death              947
is_primary_diagnosis         2
age_at_diagnosis_days       16
primary_diagnosis            1
stage                       12
pathologic_T                 1
pathologic_N                 1
pathologic_M                 1
days_to_last_follow_up    1097
dtype: int64

In [52]:
clinical_patient["age_at_diagnosis_days"] = pd.to_numeric(
    clinical_patient["age_at_diagnosis_days"],
    errors="coerce"
)

clinical_patient["age_at_diagnosis_years"] = (
    clinical_patient["age_at_diagnosis_days"] / 365.25
)

clinical_patient[
    [
        "patient_id",
        "age_at_diagnosis_days",
        "age_at_diagnosis_years"
    ]
].head(10)

     patient_id  age_at_diagnosis_days  age_at_diagnosis_years
0  TCGA-E2-A1IU                22279.0               60.996578
1  TCGA-A1-A0SB                25833.0               70.726899
2  TCGA-A2-A04W                18345.0               50.225873
3  TCGA-AN-A0AM                20713.0               56.709103
4  TCGA-LL-A440                22497.0               61.593429
5  TCGA-A7-A26E                26274.0               71.934292
6  TCGA-A8-A07W                27942.0               76.501027
7  TCGA-D8-A1XY                27106.0               74.212183
8  TCGA-EW-A1P7                21750.0               59.548255
9  TCGA-AO-A128                22340.0               61.163587

In [53]:
clinical_patient["age_at_diagnosis_years"].describe()

count    1082.000000
mean       59.101550
std        13.180320
min        26.573580
25%        49.358658
50%        59.029432
75%        68.086927
max        89.998631
Name: age_at_diagnosis_years, dtype: float64

In [54]:
followup_file = clinical_dir / "follow_up.tsv"

followup_df = pd.read_csv(
    followup_file,
    sep="\t",
    low_memory=False
)

print("Shape:", followup_df.shape)

Shape: (9427, 151)

In [55]:
followup_df.columns.tolist()

['project.project_id',
 'cases.case_id',
 'cases.submitter_id',
 'follow_ups.adverse_event',
 'follow_ups.adverse_event_grade',
 'follow_ups.barretts_esophagus_goblet_cells_present',
 'follow_ups.cause_of_response',
 'follow_ups.days_to_adverse_event',
 'follow_ups.days_to_first_event',
 'follow_ups.days_to_follow_up',
 'follow_ups.days_to_imaging',
 'follow_ups.days_to_progression',
 'follow_ups.days_to_progression_free',
 'follow_ups.days_to_recurrence',
 'follow_ups.discontiguous_lesion_count',
 'follow_ups.disease_response',
 'follow_ups.ecog_performance_status',
 'follow_ups.evidence_of_progression_type',
 'follow_ups.evidence_of_recurrence_type',
 'follow_ups.first_event',
 'follow_ups.follow_up_id',
 'follow_ups.histologic_progression',
 'follow_ups.history_of_tumor',
 'follow_ups.history_of_tumor_type',
 'follow_ups.hormone_replacement_therapy_type',
 'follow_ups.imaging_anatomic_site',
 'follow_ups.imaging_findings',
 'follow_ups.imaging_result',
 'follow_ups.imaging_suv',
 'follow_ups.imaging_suv_max',
 'follow_ups.imaging_type',
 'follow_ups.karnofsky_performance_status',
 'follow_ups.peritoneal_washing_results',
 'follow_ups.procedures_performed',
 'follow_ups.progression_or_recurrence',
 'follow_ups.progression_or_recurrence_anatomic_site',
 'follow_ups.progression_or_recurrence_type',
 'follow_ups.recist_targeted_regions_number',
 'follow_ups.recist_targeted_regions_sum',
 'follow_ups.scan_tracer_used',
 'follow_ups.submitter_id',
 'follow_ups.timepoint_category',
 'follow_ups.treatment_emergent_adverse_event',
 'follow_ups.year_of_follow_up',
 'molecular_tests.aa_change',
 'molecular_tests.aneuploidy',
 'molecular_tests.antigen',
 'molecular_tests.biospecimen_type',
 'molecular_tests.biospecimen_volume',
 'molecular_tests.blood_test_normal_range_lower',
 'molecular_tests.blood_test_normal_range_upper',
 'molecular_tests.cell_count',
 'molecular_tests.chromosomal_translocation',
 'molecular_tests.chromosome',
 'molecular_tests.chromosome_arm',
 'molecular_tests.clonality',
 'molecular_tests.copy_number',
 'molecular_tests.cytoband',
 'molecular_tests.days_to_test',
 'molecular_tests.exon',
 'molecular_tests.gene_symbol',
 'molecular_tests.histone_family',
 'molecular_tests.histone_variant',
 'molecular_tests.hpv_strain',
 'molecular_tests.intron',
 'molecular_tests.laboratory_test',
 'molecular_tests.loci_abnormal_count',
 'molecular_tests.loci_count',
 'molecular_tests.locus',
 'molecular_tests.mismatch_repair_mutation',
 'molecular_tests.mitotic_count',
 'molecular_tests.mitotic_total_area',
 'molecular_tests.molecular_analysis_method',
 'molecular_tests.molecular_consequence',
 'molecular_tests.molecular_test_id',
 'molecular_tests.mutation_codon',
 'molecular_tests.pathogenicity',
 'molecular_tests.ploidy',
 'molecular_tests.second_exon',
 'molecular_tests.second_gene_symbol',
 'molecular_tests.specialized_molecular_test',
 'molecular_tests.staining_intensity_scale',
 'molecular_tests.staining_intensity_value',
 'molecular_tests.submitter_id',
 'molecular_tests.test_analyte_type',
 'molecular_tests.test_result',
 'molecular_tests.test_units',
 'molecular_tests.test_value',
 'molecular_tests.test_value_range',
 'molecular_tests.timepoint_category',
 'molecular_tests.transcript',
 'molecular_tests.variant_origin',
 'molecular_tests.variant_type',
 'molecular_tests.zygosity',
 'other_clinical_attributes.aids_risk_factors',
 'other_clinical_attributes.bmi',
 'other_clinical_attributes.body_surface_area',
 'other_clinical_attributes.cd4_count',
 'other_clinical_attributes.cdc_hiv_risk_factors',
 'other_clinical_attributes.comorbidities',
 'other_clinical_attributes.comorbidity_method_of_diagnosis',
 'other_clinical_attributes.days_to_comorbidity',
 'other_clinical_attributes.days_to_risk_factor',
 'other_clinical_attributes.diabetes_treatment_type',
 'other_clinical_attributes.dlco_ref_predictive_percent',
 'other_clinical_attributes.exercise_frequency_weekly',
 'other_clinical_attributes.eye_color',
 'other_clinical_attributes.fertility_history',
 'other_clinical_attributes.fev1_fvc_post_bronch_percent',
 'other_clinical_attributes.fev1_fvc_pre_bronch_percent',
 'other_clinical_attributes.fev1_ref_post_bronch_percent',
 'other_clinical_attributes.fev1_ref_pre_bronch_percent',
 'other_clinical_attributes.haart_treatment_indicator',
 'other_clinical_attributes.height',
 'other_clinical_attributes.hepatitis_sustained_virological_response',
 'other_clinical_attributes.hiv_viral_load',
 'other_clinical_attributes.hormonal_contraceptive_type',
 'other_clinical_attributes.hormonal_contraceptive_use',
 'other_clinical_attributes.hormonal_replacement_therapy_status',
 'other_clinical_attributes.hormone_replacement_therapy_type',
 'other_clinical_attributes.hysterectomy_margins_involved',
 'other_clinical_attributes.hysterectomy_type',
 'other_clinical_attributes.immunosuppressive_treatment_type',
 'other_clinical_attributes.menopause_status',
 'other_clinical_attributes.myasthenia_gravis_classification',
 'other_clinical_attributes.nadir_cd4_count',
 'other_clinical_attributes.nononcologic_therapeutic_agents',
 'other_clinical_attributes.number_of_pregnancies',
 'other_clinical_attributes.other_clinical_attribute_id',
 'other_clinical_attributes.oxygen_use_indicator',
 'other_clinical_attributes.oxygen_use_type',
 'other_clinical_attributes.pancreatitis_onset_year',
 'other_clinical_attributes.pregnancy_outcome',
 'other_clinical_attributes.pregnant_at_diagnosis',
 'other_clinical_attributes.premature_at_birth',
 'other_clinical_attributes.reflux_treatment_type',
 'other_clinical_attributes.risk_factor_method_of_diagnosis',
 'other_clinical_attributes.risk_factor_treatment',
 'other_clinical_attributes.risk_factors',
 'other_clinical_attributes.submitter_id',
 'other_clinical_attributes.timepoint_category',
 'other_clinical_attributes.treatment_frequency',
 'other_clinical_attributes.undescended_testis_corrected',
 'other_clinical_attributes.undescended_testis_corrected_age_range',
 'other_clinical_attributes.undescended_testis_corrected_laterality',
 'other_clinical_attributes.undescended_testis_corrected_method',
 'other_clinical_attributes.undescended_testis_history',
 'other_clinical_attributes.undescended_testis_history_laterality',
 'other_clinical_attributes.viral_hepatitis_serology_tests',
 'other_clinical_attributes.weeks_gestation_at_birth',
 'other_clinical_attributes.weight']

In [56]:
followup_relevant_columns = [
    col for col in followup_df.columns
    if any(
        keyword in col.lower()
        for keyword in [
            "submitter",
            "case_id",
            "follow",
            "death",
            "vital",
            "progression"
        ]
    )
]

followup_relevant_columns

['cases.case_id',
 'cases.submitter_id',
 'follow_ups.adverse_event',
 'follow_ups.adverse_event_grade',
 'follow_ups.barretts_esophagus_goblet_cells_present',
 'follow_ups.cause_of_response',
 'follow_ups.days_to_adverse_event',
 'follow_ups.days_to_first_event',
 'follow_ups.days_to_follow_up',
 'follow_ups.days_to_imaging',
 'follow_ups.days_to_progression',
 'follow_ups.days_to_progression_free',
 'follow_ups.days_to_recurrence',
 'follow_ups.discontiguous_lesion_count',
 'follow_ups.disease_response',
 'follow_ups.ecog_performance_status',
 'follow_ups.evidence_of_progression_type',
 'follow_ups.evidence_of_recurrence_type',
 'follow_ups.first_event',
 'follow_ups.follow_up_id',
 'follow_ups.histologic_progression',
 'follow_ups.history_of_tumor',
 'follow_ups.history_of_tumor_type',
 'follow_ups.hormone_replacement_therapy_type',
 'follow_ups.imaging_anatomic_site',
 'follow_ups.imaging_findings',
 'follow_ups.imaging_result',
 'follow_ups.imaging_suv',
 'follow_ups.imaging_suv_max',
 'follow_ups.imaging_type',
 'follow_ups.karnofsky_performance_status',
 'follow_ups.peritoneal_washing_results',
 'follow_ups.procedures_performed',
 'follow_ups.progression_or_recurrence',
 'follow_ups.progression_or_recurrence_anatomic_site',
 'follow_ups.progression_or_recurrence_type',
 'follow_ups.recist_targeted_regions_number',
 'follow_ups.recist_targeted_regions_sum',
 'follow_ups.scan_tracer_used',
 'follow_ups.submitter_id',
 'follow_ups.timepoint_category',
 'follow_ups.treatment_emergent_adverse_event',
 'follow_ups.year_of_follow_up',
 'molecular_tests.submitter_id',
 'other_clinical_attributes.submitter_id']

In [57]:
followup_selected = followup_df[
    [
        "cases.submitter_id",
        "follow_ups.days_to_follow_up"
    ]
].copy()

followup_selected = followup_selected.rename(
    columns={
        "cases.submitter_id": "patient_id",
        "follow_ups.days_to_follow_up": "days_to_follow_up"
    }
)

followup_selected.head(10)

     patient_id days_to_follow_up
0  TCGA-E2-A1IU               337
1  TCGA-E2-A1IU               127
2  TCGA-E2-A1IU               337
3  TCGA-E2-A1IU               '--
4  TCGA-E2-A1IU               '--
5  TCGA-E2-A1IU               '--
6  TCGA-E2-A1IU               '--
7  TCGA-E2-A1IU               '--
8  TCGA-A1-A0SB               259
9  TCGA-A1-A0SB               259

In [58]:
followup_selected["days_to_follow_up"] = pd.to_numeric(
    followup_selected["days_to_follow_up"],
    errors="coerce"
)

In [59]:
print("Total follow-up rows:", len(followup_selected))
print(
    "Unique patients:",
    followup_selected["patient_id"].nunique()
)
print(
    "Non-missing follow-up times:",
    followup_selected["days_to_follow_up"].notna().sum()
)

Total follow-up rows: 9427
Unique patients: 1096
Non-missing follow-up times: 3362

In [60]:
followup_selected["days_to_follow_up"].describe()

count    3362.000000
mean     1107.183819
std      1151.269658
min       -31.000000
25%       364.250000
50%       715.000000
75%      1534.750000
max      8605.000000
Name: days_to_follow_up, dtype: float64

In [61]:
latest_followup = (
    followup_selected
    .dropna(subset=["patient_id", "days_to_follow_up"])
    .groupby("patient_id", as_index=False)["days_to_follow_up"]
    .max()
)

latest_followup = latest_followup.rename(
    columns={
        "days_to_follow_up": "latest_follow_up_days"
    }
)

latest_followup.head()

     patient_id  latest_follow_up_days
0  TCGA-3C-AAAU                 4047.0
1  TCGA-3C-AALI                 4005.0
2  TCGA-3C-AALJ                 1474.0
3  TCGA-3C-AALK                 1448.0
4  TCGA-4H-AAAK                  348.0

In [62]:
print("Patients with usable follow-up:",
      latest_followup["patient_id"].nunique())

latest_followup["latest_follow_up_days"].describe()

Patients with usable follow-up: 1096

count    1096.000000
mean     1232.410584
std      1192.038846
min        -7.000000
25%       441.750000
50%       821.500000
75%      1673.000000
max      8605.000000
Name: latest_follow_up_days, dtype: float64

In [63]:
latest_followup[
    latest_followup["latest_follow_up_days"] < 0
]

        patient_id  latest_follow_up_days
1072  TCGA-PL-A8LV                   -7.0

In [64]:
(latest_followup["latest_follow_up_days"] < 0).sum()

np.int64(1)

In [65]:
latest_followup.loc[
    latest_followup["latest_follow_up_days"] < 0,
    "latest_follow_up_days"
] = np.nan

print(
    "Negative follow-up values:",
    (latest_followup["latest_follow_up_days"] < 0).sum()
)

print(
    "Patients with usable follow-up:",
    latest_followup["latest_follow_up_days"].notna().sum()
)

Negative follow-up values: 0
Patients with usable follow-up: 1095

In [66]:
clinical_patient = clinical_patient.merge(
    latest_followup,
    on="patient_id",
    how="left"
)

print("Rows:", len(clinical_patient))
print("Unique patients:", clinical_patient["patient_id"].nunique())
print(
    "Duplicated patient IDs:",
    clinical_patient["patient_id"].duplicated().sum()
)

print(
    "Missing latest follow-up:",
    clinical_patient["latest_follow_up_days"].isna().sum()
)

Rows: 1098
Unique patients: 1098
Duplicated patient IDs: 0
Missing latest follow-up: 3

In [67]:
clinical_patient["vital_status"].value_counts(dropna=False)

vital_status
Alive    945
Dead     152
NaN        1
Name: count, dtype: int64

In [68]:
clinical_patient.groupby("vital_status")[
    ["days_to_death", "latest_follow_up_days"]
].count()

              days_to_death  latest_follow_up_days
vital_status
Alive                     0                    943
Dead                    151                    152

In [69]:
clinical_patient["days_to_death"] = pd.to_numeric(
    clinical_patient["days_to_death"],
    errors="coerce"
)

In [70]:
clinical_patient["overall_survival_event"] = np.select(
    [
        clinical_patient["vital_status"].eq("Dead"),
        clinical_patient["vital_status"].eq("Alive")
    ],
    [
        1,
        0
    ],
    default=np.nan
)

In [71]:
clinical_patient["overall_survival_event"].value_counts(
    dropna=False
)

overall_survival_event
0.0    945
1.0    152
NaN      1
Name: count, dtype: int64

In [72]:
clinical_patient["overall_survival_days"] = np.where(
    clinical_patient["vital_status"].eq("Dead"),
    clinical_patient["days_to_death"],
    np.where(
        clinical_patient["vital_status"].eq("Alive"),
        clinical_patient["latest_follow_up_days"],
        np.nan
    )
)

In [73]:
clinical_patient[
    [
        "patient_id",
        "vital_status",
        "days_to_death",
        "latest_follow_up_days",
        "overall_survival_days",
        "overall_survival_event"
    ]
].head(10)

,patient_id,vital_status,days_to_death,latest_follow_up_days,overall_survival_days,overall_survival_event
0,TCGA-E2-A1IU,Alive,NaN,337.0,337.0,0.0
1,TCGA-A1-A0SB,Alive,NaN,259.0,259.0,0.0
2,TCGA-A2-A04W,Alive,NaN,3102.0,3102.0,0.0
3,TCGA-AN-A0AM,Alive,NaN,5.0,5.0,0.0
4,TCGA-LL-A440,Alive,NaN,759.0,759.0,0.0
5,TCGA-A7-A26E,Alive,NaN,954.0,954.0,0.0
6,TCGA-A8-A07W,Alive,NaN,304.0,304.0,0.0
7,TCGA-D8-A1XY,Alive,NaN,503.0,503.0,0.0
8,TCGA-EW-A1P7,Alive,NaN,915.0,915.0,0.0
9,TCGA-AO-A128,Alive,NaN,3248.0,3248.0,0.0

In [74]:
print(
    "Patients with OS time:",
    clinical_patient["overall_survival_days"].notna().sum()
)

print(
    "Patients with OS event:",
    clinical_patient["overall_survival_event"].notna().sum()
)

survival_complete = clinical_patient[
    clinical_patient["overall_survival_days"].notna()
    & clinical_patient["overall_survival_event"].notna()
].copy()

print("Patients usable for survival analysis:", len(survival_complete))

Patients with OS time: 1094
Patients with OS event: 1097
Patients usable for survival analysis: 1094

In [75]:
clinical_patient["overall_survival_days"].describe()

count    1094.000000
mean     1234.646252
std      1191.979316
min         0.000000
25%       446.000000
50%       823.500000
75%      1673.000000
max      8605.000000
Name: overall_survival_days, dtype: float64

In [76]:
print(
    "Negative OS times:",
    (clinical_patient["overall_survival_days"] < 0).sum()
)

Negative OS times: 0

In [77]:
final_columns = [
    "case_id",
    "patient_id",
    "sex",
    "race",
    "ethnicity",

    "age_at_diagnosis_days",
    "age_at_diagnosis_years",
    "primary_diagnosis",
    "stage",
    "pathologic_T",
    "pathologic_N",
    "pathologic_M",

    "vital_status",
    "days_to_death",
    "latest_follow_up_days",
    "overall_survival_days",
    "overall_survival_event"
]

clinical_clean = clinical_patient[final_columns].copy()

clinical_clean.head()

,case_id,patient_id,sex,race,ethnicity,age_at_diagnosis_days,age_at_diagnosis_years,primary_diagnosis,stage,pathologic_T,pathologic_N,pathologic_M,vital_status,days_to_death,latest_follow_up_days,overall_survival_days,overall_survival_event
0,001cef41-ff86-4d3f-a140-a647ac4b10a1,TCGA-E2-A1IU,female,white,not hispanic or latino,22279.0,60.996578,"Infiltrating duct carcinoma, NOS",Stage IA,T1c,N0 (mol+),M0,Alive,NaN,337.0,337.0,0.0
1,0045349c-69d9-4306-a403-c9c1fa836644,TCGA-A1-A0SB,female,white,not hispanic or latino,25833.0,70.726899,Adenoid cystic carcinoma,Stage I,T1c,N0,M0,Alive,NaN,259.0,259.0,0.0
2,00807dae-9f4a-4fd1-aac2-82eb11bf2afb,TCGA-A2-A04W,female,white,not hispanic or latino,18345.0,50.225873,Apocrine adenocarcinoma,Stage IIB,T2,N1mi,M0,Alive,NaN,3102.0,3102.0,0.0
3,00a2d166-78c9-4687-a195-3d6315c27574,TCGA-AN-A0AM,female,white,not hispanic or latino,20713.0,56.709103,"Infiltrating duct carcinoma, NOS",Stage IIA,T2,N0,M0,Alive,NaN,5.0,5.0,0.0
4,00b11ca8-8540-4a3d-b602-ec754b00230b,TCGA-LL-A440,female,white,not hispanic or latino,22497.0,61.593429,"Lobular carcinoma, NOS",Stage IA,T1c,N0 (i-),MX,Alive,NaN,759.0,759.0,0.0

In [78]:
print("Final dataset shape:", clinical_clean.shape)
print("Unique patients:", clinical_clean["patient_id"].nunique())
print("Duplicated patients:", clinical_clean["patient_id"].duplicated().sum())

print(
    "Patients usable for survival:",
    clinical_clean[
        clinical_clean["overall_survival_days"].notna()
        & clinical_clean["overall_survival_event"].notna()
    ].shape[0]
)

Final dataset shape: (1098, 17)
Unique patients: 1098
Duplicated patients: 0
Patients usable for survival: 1094

In [79]:
from pathlib import Path

processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

output_file = processed_dir / "tcga_brca_clinical_clean.csv"

clinical_clean.to_csv(
    output_file,
    index=False
)

print("Saved to:", output_file)

Saved to: ../data/processed/tcga_brca_clinical_clean.csv

In [80]:
print(output_file.exists())

True